"""
Multi-Agent Virtual Assistant API

This FastAPI application serves as the backend for a multi-agent virtual assistant platform.
It supports interactions with multiple specialized agents: a general assistant, an AI-focused
LLM service, and a Concordia-specific LLM service. The API supports processing user prompts
and collecting feedback for continual improvement of agent responses.

Endpoints:
----------

1. GET /
   - Returns a welcome message.
   - Useful to verify if the API is running.

2. POST /process/
   - Accepts a user prompt and an agent identifier.
   - Routes the prompt to the appropriate agent for processing.
   - Agents:
       * "general": Routes to general_assistant.get_response.
       * "ai": Routes to ai_llm_service.ai_qa.
       * any other value: Routes to concordia_llm_service.generate_response.

   Request Body (JSON):
   {
       "user_prompt": "What is the capital of France?",
       "agent": "general"
   }

   Response (JSON):
   {
       "response": "Paris is the capital of France."
   }

3. POST /feedback/
   - Accepts user feedback for a specific agent.
   - Routes the feedback to the corresponding agent's update_feedback method.

   Request Body (JSON):
   {
       "agent": "general",
       "feedback": "The response was helpful."
   }

   Response (JSON):
   {
       "response": "Got the feedback The response was helpful. from general Agent"
   }

Modules Used:
-------------
- general_assistant: Contains general-purpose conversational agent logic.
- ai_llm_service: Handles domain-specific queries related to artificial intelligence.
- concordia_llm_service: Tailored to Concordia-related services or information.

To Run:
-------
Use the following command:
    uvicorn main:app --reload
"""

from fastapi import FastAPI, Query
from pydantic import BaseModel
import uvicorn
import os

from backend.chat_agents import general_assistant
from backend.chat_agents import ai_llm_service
from backend.chat_agents import concordia_llm_service

app = FastAPI()


@app.get("/")
async def root():
    """
    Root endpoint to verify the server is running.

    Returns:
        dict: A welcome message.
    """
    return {"message": "Welcome to Multi-Agent Virtual Assistant"}


class ProcessRequestBody(BaseModel):
    """
    Schema for processing user prompts.

    Attributes:
        user_prompt (str): The user's input prompt.
        agent (str): The target agent to handle the prompt.
    """
    user_prompt: str
    agent: str


class FeedbackRequestBody(BaseModel):
    """
    Schema for collecting feedback on agent responses.

    Attributes:
        agent (str): The agent to which the feedback pertains.
        feedback (str): User feedback text.
    """
    agent: str
    feedback: str


@app.post("/process/")
async def process_prompt(request_data: ProcessRequestBody):
    """
    Processes a user prompt through the specified agent.

    Args:
        request_data (ProcessRequestBody): The user input and target agent.

    Returns:
        dict: The response generated by the corresponding agent.
    """
    try:
        user_prompt = request_data.user_prompt
        agent = request_data.agent
        if agent == "general":
            return {"response": general_assistant.get_response(user_prompt)}
        elif agent == "ai":
            return {"response": ai_llm_service.ai_qa(user_prompt)}
        else:
            return {"response": concordia_llm_service.generate_response(user_prompt)}
    except Exception as e:
        print(f"Error generating response: {e}")
        return {"response": "Sorry, I encountered an error while processing your request. Please try again!!"}


@app.post("/feedback/")
async def process_request(feedback_data: FeedbackRequestBody):
    """
    Collects and updates feedback for a specific agent.

    Args:
        feedback_data (FeedbackRequestBody): Contains the agent name and feedback text.

    Returns:
        dict: Acknowledgment message indicating successful feedback submission.
    """
    try:
        agent_mode = feedback_data.agent
        feedback = feedback_data.feedback
        if agent_mode == "general":
            general_assistant.update_feedback(feedback_data.feedback)
        elif agent_mode == "ai":
            ai_llm_service.update_feedback(feedback_data.feedback)
        else:
            concordia_llm_service.update_feedback(feedback_data.feedback)

        response = f'Got the feedback {feedback} from {agent_mode} Agent'
        return {"response": response}
    except Exception as e:
        print(f"Error updating feedback: {e}")
        return {"response": "Error while updating feedback. Please try again!!"}


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)
